name: FX_HD_NO_LAG_BUFFER

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Smooth Stream
        env:
          URL: ${{ secrets.STREAM_URL_FX }}
          KEY: ${{ secrets.TELEGRAM_KEY_FX }}
        run: |
          while true; do
            echo "🎬 Запуск с анти-фриз буфером: 4500kbps..."
            
            # Добавлены параметры буферизации (-thread_queue_size и -fifo_size)
            # Снижен битрейт до 4500k (золотая середина для Telegram)
            ffmpeg -re \
              -thread_queue_size 1024 \
              -protocol_whitelist file,http,https,tcp,tls \
              -user_agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36" \
              -headers "Accept: */*"$'\r\n'"Origin: https://player.uspeh-bil.ru"$'\r\n'"Referer: https://player.uspeh-bil.ru/" \
              -i "$URL" \
              -vf "unsharp=3:3:0.5:3:3:0.2" \
              -vcodec libx264 -preset superfast -crf 21 -tune film \
              -b:v 4500k -maxrate 5500k -bufsize 10000k \
              -pix_fmt yuv420p -g 50 \
              -c:a aac -b:a 128k -ar 44100 \
              -f flv "$KEY" || echo "⚠️ Сеть моргнула. Перезапуск..."

            echo "🔄 Рестарт через 5 секунд..."
            sleep 5
          done
