name: CN_ULTRA_HD_BRANDED

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Branded Stealth Stream
        env:
          KEY: ${{ secrets.TELEGRAM_KEY }}
        run: |
          URL="http://176.118.197.101/Cartoon_Network/index.m3u8"
          
          echo "🚀 Запуск брендированного вещания @cnworldwide..."

          # Добавили фильтр drawtext: шрифт стандартный, цвет белый с прозрачностью 0.5
          # x=w-tw-50 (отступ 50 пкс справа), y=50 (отступ 50 пкс сверху)
          
          timeout 350m ffmpeg -re \
            -headers "User-Agent: VLC/3.0.18 LibVLC/3.0.18" \
            -headers "Referer: http://176.118.197.101/" \
            -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 30 \
            -thread_queue_size 8192 \
            -i "$URL" \
            -vf "unsharp=5:5:1.2:5:5:0.6,drawtext=text='@cnworldwide':x=w-tw-50:y=50:fontsize=40:fontcolor=white@0.5:shadowcolor=black:shadowx=2:shadowy=2" \
            -vcodec libx264 -preset superfast -crf 17 -tune animation \
            -b:v 9000k -maxrate 11000k -bufsize 18000k \
            -pix_fmt yuv420p -g 50 \
            -c:a aac -b:a 192k -ar 48000 \
            -f flv "$KEY"
