name: Nickelodeon Ultra HD 7K

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg curl

      - name: Start Ultra Stream
        env:
          URL: ${{ secrets.STREAM_URL_NICK }}
          KEY: ${{ secrets.TELEGRAM_KEY_NICK }}
        run: |
          while true; do
            echo "🔎 Проверка стабильной ссылки..."
            
            STATUS=$(curl -o /dev/null -s -w "%{http_code}" -I -L "$URL" \
              -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")
            
            if [ "$STATUS" -ne 200 ] && [ "$STATUS" -ne 302 ]; then
              echo "❌ Ошибка ссылки! Код: $STATUS. Ждем 30 сек..."
              sleep 30
              continue
            fi

            echo "✅ Ссылка активна! Запуск потока 7000kbps..."
            
            # -protocol_whitelist: разрешаем все виды соединений
            # -b:v 7000k: устанавливаем мощный битрейт
            # -preset veryfast: баланс между качеством и нагрузкой на CPU GitHub
            ffmpeg -re \
              -protocol_whitelist file,http,https,tcp,tls \
              -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" \
              -headers "Referer: https://www.google.com/" \
              -i "$URL" \
              -vcodec libx264 -preset veryfast -b:v 7000k -maxrate 9000k -bufsize 14000k \
              -pix_fmt yuv420p -g 50 -c:a aac -b:a 192k -ar 48000 \
              -f flv "$KEY" || echo "⚠️ Поток прерван."

            echo "🔄 Перезапуск через 5 секунд..."
            sleep 5
          done
