name: NICKELODEON_HD_STABLE

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Nick Stream Loop
        env:
          # Заменил на твой секрет
          KEY: ${{ secrets.TELEGRAM_KEY_NICK }}
          STREAM_URL_NICK: "http://s06.wsbof.com:8080/s/f2507226/nickelodeon-hd.m3u8"
        run: |
          echo "📡 Запуск Nickelodeon HD (9.5 Mbps) с ключом NICK..."
          
          while true; do
            echo "🎬 Эфир пошел..."
            
            ffmpeg -re \
              -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
              -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 2 \
              -fflags +genpts+discardcorrupt \
              -i "$STREAM_URL_NICK" \
              -vcodec libx264 -preset ultrafast -tune animation \
              -b:v 9500k -maxrate 11000k -bufsize 18000k \
              -pix_fmt yuv420p -g 100 \
              -af "volume=1.2" \
              -c:a aac -b:a 256k -ar 48000 \
              -f flv "$KEY" || echo "⚠️ Поток прерван..."
              
            echo "🔄 Переподключение к Нику через 3 секунды..."
            sleep 3
          done
