name: MTProto Proxy Localtonet
on: 
  workflow_dispatch: # Запуск вручную кнопкой Run Workflow

jobs:
  run-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Start MTProto Docker
        run: |
          # Запускаем сам прокси-сервер внутри GitHub Actions
          docker run -d -p 3128:443 --name=mtproto-proxy \
          -e SECRET=549a35f83d32320233b59f743fb2c957 \
          telegrammessenger/proxy:latest

      - name: Install and Run Localtonet
        run: |
          # Скачиваем и распаковываем клиент туннеля
          curl -L https://localtonet.com/download/localtonet-linux-x64.zip -o localtonet.zip
          unzip localtonet.zip
          chmod +x localtonet
          
          # 1. Привязываем твой AuthToken
          ./localtonet authtoken OdMPknfiCHqsTX4vDWV3artcmjKYxeB8N
          
          # 2. Запускаем TCP туннель на порт прокси (3128)
          # Используем nohup и &, чтобы процесс шел в фоне, и мы могли видеть логи
          ./localtonet tcp -p 3128
