name: Narcos TV Final

on:
  schedule:
    - cron: '0 */6 * * *' # Перезапуск каждые 6 часов
  workflow_dispatch: # Ручной запуск

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Narcos Marathon
        env:
          STREAM_URL: ${{ secrets.STREAM_URL_NARCOS }}
          TELEGRAM_KEY: ${{ secrets.TELEGRAM_KEY_NARCOS }}
        run: |
          while true; do
            echo "🚀 Запуск трансляции Narcos в 1080p (6000k)..."
            
            # -re: читать в реальном времени
            # -stream_loop -1: крутить файл бесконечно (если хочешь 24/7 одну серию)
            # Если хочешь, чтобы серия просто прошла один раз, убери -stream_loop -1
            ffmpeg -re -stream_loop -1 -i "$STREAM_URL" \
            -vcodec libx264 -preset superfast -b:v 6000k -maxrate 8000k -bufsize 12000k \
            -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -ar 44100 \
            -f flv "$TELEGRAM_KEY" || true
            
            echo "🔄 Обрыв связи или конец файла. Перезапуск через 10 секунд..."
            sleep 10
          done
